# Generated by Django 3.2.9 on 2021-11-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('teg', models.CharField(max_length=150, verbose_name='Теги')),
                ('body', models.CharField(max_length=150, verbose_name='Описание')),
                ('user', models.CharField(max_length=150, verbose_name='Пользователь')),
                ('info', models.CharField(max_length=150, verbose_name='Информация')),
                ('hab', models.CharField(max_length=150, verbose_name='Хабы')),
                ('time', models.CharField(max_length=150, verbose_name='Время')),
                ('image', models.CharField(max_length=150, verbose_name='Кратинка')),
                ('vote', models.CharField(max_length=150, verbose_name='Голосы')),
                ('bookmarks', models.CharField(max_length=150, verbose_name='Избранные')),
                ('contact', models.CharField(max_length=150, verbose_name='Контакт')),
                ('user_content_karma', models.CharField(max_length=150, verbose_name='Карма Пользователя')),
                ('user_content_rate', models.CharField(max_length=150, verbose_name='Рейтинг Пользователя')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
